# AUTO-GENERATED by src/codegen/env_compiler.py  —  do not edit
from __future__ import annotations
import math, struct, time
import numpy as np
import pymem
import pymem.memory as _pmmem
import gymnasium as gym
import pydirectinput

# ── Compiled state map ────────────────────────────────────────────────────────
GAME_NAME    = "python"
GAME_EXE     = "python.exe"
TICK_SLEEP   = 0.5    # seconds between action and next obs read
FREEZE_STEPS = 10             # consecutive identical obs -> terminated (menu safeguard)
STRUCT_WIN   = 512            # byte window searched around anchor for sibling fields

STATE_VARS: dict[str, dict] = {
    'health': {
        "min":         0.0,
        "max":         100.0,
        "initial":     100.0,
        "role":        'health',
        "dynamic_only":True,
        "offsets":     [],
    },
    'pos_x': {
        "min":         0.0,
        "max":         100.0,
        "initial":     None,
        "role":        'coordinate_x',
        "dynamic_only":True,
        "offsets":     [],
    },
}

ACTIONS: list[str]          = ['MOVE_UP', 'MOVE_DOWN', 'MOVE_LEFT', 'MOVE_RIGHT']
ACTION_KEYS: dict[str, str] = {'MOVE_UP': 'w', 'MOVE_DOWN': 's', 'MOVE_LEFT': 'a', 'MOVE_RIGHT': 'd'}
HEALTH_IDX: int             = 0   # index of health var in obs vector

# ── Memory constants ──────────────────────────────────────────────────────────
_MEM_COMMIT = 0x1000
_PAGE_RW    = 0x04   # PAGE_READWRITE
_PAGE_RWX   = 0x40   # PAGE_EXECUTE_READWRITE
_MAX_ADDR   = 0x7FFFFFFF0000


def _open_process(pid: int) -> pymem.Pymem:
    """
    Open a process for VM-read access using the minimum required rights.
    Falls back to full access if the restricted open fails (e.g., running as admin).
    """
    import ctypes
    _PROCESS_VM_READ        = 0x0010
    _PROCESS_QUERY_INFO     = 0x0400
    pm = pymem.Pymem()
    pm.process_id = pid
    handle = ctypes.windll.kernel32.OpenProcess(
        _PROCESS_VM_READ | _PROCESS_QUERY_INFO, False, pid
    )
    if not handle:
        # Escalate to full access (requires admin / SeDebugPrivilege)
        pm.open_process_from_id(pid)
    else:
        pm.process_handle = handle
    return pm


def _scan_float(pm: pymem.Pymem, value: float) -> list[int]:
    """Walk all committed RW/RWX pages and collect 4-byte float-aligned matches."""
    pat  = struct.pack("<f", value)
    hits: list[int] = []
    addr = 0x10000
    while addr < _MAX_ADDR:
        try:
            mbi = _pmmem.virtual_query(pm.process_handle, addr)
        except Exception:
            addr += 0x1000
            continue
        base, size = int(mbi.BaseAddress), int(mbi.RegionSize)
        if mbi.State == _MEM_COMMIT and mbi.Protect in (_PAGE_RW, _PAGE_RWX):
            try:
                buf = pm.read_bytes(base, size)
                i = 0
                while i <= len(buf) - 4:
                    if buf[i : i + 4] == pat:
                        hits.append(base + i)
                    i += 4
            except OSError:
                pass
        nxt = base + size
        if nxt <= addr:
            break
        addr = nxt
    return hits


def _find_game_addresses(
    pm: pymem.Pymem,
    state_vars: dict[str, dict],
    hint_values: dict[str, float] | None = None,
) -> dict[str, int]:
    """
    Locate all state variable addresses for the current session.

    For each non-anchor variable the search order is:
      1. hint_values override (e.g. from reset options)
      2. STATE_VARS["initial"] if not None  → exact-match within struct window
      3. Independent full-process float scan → proximity-intersect with anchor

    Approach 3 handles the case where initial_scan_value was not stored in the
    state_map (e.g. an old map generated before env_compiler v2).  It is slower
    (~same cost as the anchor scan) but always correct.
    """
    hints = hint_values or {}

    anchor = next(
        (n for n, v in state_vars.items() if "health" in v.get("role", "")),
        next(iter(state_vars)),
    )
    anchor_val = float(hints.get(anchor, state_vars[anchor]["initial"]))
    anchor_hits = _scan_float(pm, anchor_val)

    if not anchor_hits:
        print(f"[LiveEnv] WARN: no scan hits for anchor '{anchor}'={anchor_val}")
        return {n: 0 for n in state_vars}

    # Pre-scan variables whose initial is None (independent scan, proximity intersect)
    independent: dict[str, set[int]] = {}
    for name, var in state_vars.items():
        if name == anchor:
            continue
        if hints.get(name) is not None or var.get("initial") is not None:
            continue  # exact match path, no pre-scan needed
        lo, hi = float(var["min"]), float(var["max"])
        span   = hi - lo
        # Scan for a mid-range sentinel to avoid picking boundary constants (0.0, max).
        # We collect all floats strictly inside [lo + 5% range, hi - 5% range].
        hits_mid: list[int] = []
        for probe in [lo + span * 0.05, lo + span * 0.1, lo + span * 0.25, lo + span * 0.5]:
            if span == 0:
                break
            h = _scan_float(pm, probe)
            hits_mid.extend(h)
        # Also collect entire RW-page floats strictly in range — fast set for intersection
        all_range_hits: set[int] = set()
        addr = 0x10000
        pat_lo = struct.pack("<f", lo)
        while addr < _MAX_ADDR:
            try:
                mbi = _pmmem.virtual_query(pm.process_handle, addr)
            except Exception:
                addr += 0x1000
                continue
            base, size = int(mbi.BaseAddress), int(mbi.RegionSize)
            if mbi.State == _MEM_COMMIT and mbi.Protect in (_PAGE_RW, _PAGE_RWX):
                try:
                    buf = pm.read_bytes(base, size)
                    i = 0
                    while i <= len(buf) - 4:
                        try:
                            f = struct.unpack_from("<f", buf, i)[0]
                            if math.isfinite(f) and lo < f < hi:
                                all_range_hits.add(base + i)
                        except Exception:
                            pass
                        i += 4
                except OSError:
                    pass
            nxt = base + size
            if nxt <= addr:
                break
            addr = nxt
        independent[name] = all_range_hits

    for base_addr in anchor_hits:
        assigned: set[int] = {base_addr}
        result: dict[str, int] = {anchor: base_addr}

        # Window starts AT anchor — avoids reading pre-allocation memory
        win_start = base_addr
        win_bytes = STRUCT_WIN
        try:
            window = pm.read_bytes(win_start, win_bytes)
        except OSError:
            continue

        ok = True
        for name, var in state_vars.items():
            if name == anchor:
                continue

            hint = hints.get(name)
            expected: float | None = hint if hint is not None else var.get("initial")
            lo, hi = float(var["min"]), float(var["max"])
            best: int | None = None

            if expected is not None:
                # Exact match inside struct window
                for off in range(0, len(window) - 3, 4):
                    cand = win_start + off
                    if cand in assigned:
                        continue
                    try:
                        f = struct.unpack_from("<f", window, off)[0]
                    except Exception:
                        continue
                    if math.isfinite(f) and abs(f - float(expected)) < 0.01:
                        best = cand
                        break
            else:
                # No known initial — intersect independent scan with struct window
                ind_set = independent.get(name, set())
                for off in range(0, len(window) - 3, 4):
                    cand = win_start + off
                    if cand in assigned or cand not in ind_set:
                        continue
                    best = cand
                    break

            if best is None:
                ok = False
                break
            result[name] = best
            assigned.add(best)

        if ok and len(result) == len(state_vars):
            return result

    print("[LiveEnv] WARN: partial struct resolution — using anchor-only fallback")
    out: dict[str, int] = {anchor: anchor_hits[0]}
    for n in state_vars:
        out.setdefault(n, 0)
    return out


# ── Gymnasium environment ─────────────────────────────────────────────────────

class LiveEnv(gym.Env):
    """
    Auto-generated real-time environment for GAME_NAME.
    Reads game state via pymem pointer resolution and sends actions via pydirectinput.
    """
    metadata = {"render_modes": []}

    def __init__(self, game_exe: str = GAME_EXE, tick_sleep: float = TICK_SLEEP) -> None:
        super().__init__()
        n = len(STATE_VARS)
        self.observation_space = gym.spaces.Box(
            low=np.float32(0.0), high=np.float32(1.0),
            shape=(n,), dtype=np.float32,
        )
        self.action_space      = gym.spaces.Discrete(len(ACTIONS))
        self._exe              = game_exe
        self._tick             = tick_sleep
        self._pm: pymem.Pymem | None = None
        self._addrs: dict[str, int]  = {}
        self._prev_obs: np.ndarray | None = None
        self._freeze_n         = 0

    # ── Gymnasium API ─────────────────────────────────────────────────────────

    def reset(self, *, seed: int | None = None, options: dict | None = None):
        super().reset(seed=seed)
        opts  = options or {}
        hints = opts.get("initial_values")
        pid   = opts.get("pid")          # explicit PID overrides name-based attach
        # Re-attach when PID changes (new game session)
        if self._pm is None or (pid and self._pm.process_id != pid):
            self._pm = _open_process(int(pid)) if pid else pymem.Pymem(self._exe)
        self._addrs    = _find_game_addresses(self._pm, STATE_VARS, hints)
        self._prev_obs = None
        self._freeze_n = 0
        obs = self._get_obs()
        return obs, {"addrs": {k: hex(v) for k, v in self._addrs.items()}}

    def step(self, action: int):
        pydirectinput.press(ACTION_KEYS[ACTIONS[action]])
        time.sleep(self._tick)
        obs        = self._get_obs()
        terminated = self._is_terminated(obs)
        reward     = self._compute_reward(obs)
        return obs, reward, terminated, False, {}

    def close(self) -> None:
        self._pm    = None
        self._addrs = {}

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _get_obs(self) -> np.ndarray:
        pm  = self._pm
        out = np.zeros(len(STATE_VARS), dtype=np.float32)
        for i, (name, var) in enumerate(STATE_VARS.items()):
            addr = self._addrs.get(name, 0)
            if not addr:
                continue
            try:
                raw = pm.read_float(addr)
            except OSError:
                continue
            lo, hi = var["min"], var["max"]
            out[i] = float(np.clip((raw - lo) / max(hi - lo, 1e-9), 0.0, 1.0))
        return out

    def _compute_reward(self, obs: np.ndarray) -> float:
        prev = self._prev_obs
        if prev is None:
            self._prev_obs = obs.copy()
            return 0.0
        r = (obs[0] - prev[0]) * 10.0 + abs(obs[1] - prev[1]) * 0.5
        self._prev_obs = obs.copy()
        return float(np.clip(r, -10.0, 10.0))

    def _is_terminated(self, obs: np.ndarray) -> bool:
        # Dead
        if obs[HEALTH_IDX] <= 0.0:
            return True
        # Memory detached / all zeros — process may have closed
        if not np.isfinite(obs).all() or np.all(obs == 0.0):
            return True
        # Freeze safeguard: menu / loading screen / stuck state
        if self._prev_obs is not None and np.allclose(obs, self._prev_obs, atol=1e-4):
            self._freeze_n += 1
            if self._freeze_n >= FREEZE_STEPS:
                return True
        else:
            self._freeze_n = 0
        return False
