from __future__ import annotations

import json
from pathlib import Path


def generate_sdk_env(contract_dir: str | Path, output: str | Path | None = None) -> Path:
    root = Path(contract_dir).resolve()
    manifest = json.loads((root / "contract.json").read_text(encoding="utf-8"))
    out = Path(output).resolve() if output else root / "sdk_env_generated.py"
    adapter = manifest["adapter"].replace("\\", "\\\\")

    code = f'''# AUTO-GENERATED by src.sdk.generator - do not edit
from __future__ import annotations

from src.sdk.env import SDKGymEnv
from src.sdk.loader import load_adapter

ADAPTER_PATH = r"{adapter}"


def make_env(max_steps: int = 200) -> SDKGymEnv:
    load_adapter(ADAPTER_PATH)
    return SDKGymEnv(max_steps=max_steps)


class BridgeMakerGeneratedEnv(SDKGymEnv):
    def __init__(self, max_steps: int = 200):
        load_adapter(ADAPTER_PATH)
        super().__init__(max_steps=max_steps)
'''
    out.write_text(code, encoding="utf-8")
    return out
