# =====================================================================
# WARNING: AUTO-GENERATED BY THE AGENT GENERATOR. DO NOT EDIT BY HAND.
# Generated from state map: test_game_binary
# =====================================================================

import numpy as np
import gymnasium as gym
from gymnasium import spaces
from typing import Dict, Any, Tuple, Optional
from src.config import SDKConfig
from src.reward_generator import MultiObjectiveRewardGenerator
from src.logger import SDKLogger


class RLGameTestingEnvGenerated(gym.Env):
    """Dynamically compiled environment matching the discovered telemetry schema."""
    metadata = {"render_modes": ["human", "rgb_array"]}

    def __init__(self, config: SDKConfig, logger: Optional[SDKLogger] = None):
        super().__init__()
        self.config = config
        self.logger = logger

        self.map_width, self.map_height = self.config.map_size
        self.max_steps = self.config.max_steps_per_episode
        self.agent_radius = 1.0

        self.action_space = spaces.Discrete(5)
        self.action_vectors = {
            0: np.array([0.0, 1.0]),  # MOVE_UP
            1: np.array([0.0, -1.0]),  # MOVE_DOWN
            2: np.array([-1.0, 0.0]),  # MOVE_LEFT
            3: np.array([1.0, 0.0]),  # MOVE_RIGHT
            4: np.array([0.0, 0.0]),  # IDLE
        }
        self.step_speed = 3.5

        self.observation_space = spaces.Box(
            low=0.0, high=2.0, shape=(6,), dtype=np.float32
        )

        self.reward_generator = MultiObjectiveRewardGenerator(self.config, obs_dim=6)

        self.agent_pos = np.array(self.config.start_pos_agent, dtype=np.float32)
        self.prev_agent_pos = np.copy(self.agent_pos)
        self.player_pos = np.array(self.config.start_pos_player, dtype=np.float32)
        self.goal_pos = np.array(self.config.goal_pos, dtype=np.float32)
        self.health = 100.0
        self.current_step = 0
        self.npc_patrol_angle = 0.0

    def reset(self, seed: Optional[int] = None, options: Optional[Dict[str, Any]] = None) -> Tuple[np.ndarray, Dict[str, Any]]:
        super().reset(seed=seed)
        self.agent_pos = np.array(self.config.start_pos_agent, dtype=np.float32)
        self.prev_agent_pos = np.copy(self.agent_pos)
        self.player_pos = np.array(self.config.start_pos_player, dtype=np.float32)
        self.health = 100.0
        self.current_step = 0
        self.npc_patrol_angle = 0.0
        self.reward_generator.reset()
        obs = self._get_obs()
        info = {"agent_pos": self.agent_pos.tolist(), "player_pos": self.player_pos.tolist(),
                "health": self.health, "anomaly_detected": False}
        return obs, info

    def step(self, action: int) -> Tuple[np.ndarray, float, bool, bool, Dict[str, Any]]:
        self.current_step += 1
        self.prev_agent_pos = np.copy(self.agent_pos)
        prev_obs = self._get_obs()
        self.reward_generator.update_action_history(action)

        if self.config.mode == "npc":
            self.npc_patrol_angle += 0.04
            radius = 20.0
            center_x, center_y = self.config.start_pos_player
            self.player_pos[0] = np.clip(center_x + radius * np.cos(self.npc_patrol_angle), 0.0, self.map_width)
            self.player_pos[1] = np.clip(center_y + radius * np.sin(self.npc_patrol_angle), 0.0, self.map_height)

        movement_vec = self.action_vectors.get(action, np.array([0.0, 0.0])) * self.step_speed
        intended_pos = self.agent_pos + movement_vec

        hit_boundary = False
        hit_obstacle = False
        if intended_pos[0] < self.agent_radius or intended_pos[0] > (self.map_width - self.agent_radius):
            hit_boundary = True
            intended_pos[0] = np.clip(intended_pos[0], self.agent_radius, self.map_width - self.agent_radius)
        if intended_pos[1] < self.agent_radius or intended_pos[1] > (self.map_height - self.agent_radius):
            hit_boundary = True
            intended_pos[1] = np.clip(intended_pos[1], self.agent_radius, self.map_height - self.agent_radius)

        for obs_rect in self.config.obstacles:
            if obs_rect.get("type") == "rect":
                ox, oy, ow, oh = obs_rect["x"], obs_rect["y"], obs_rect["w"], obs_rect["h"]
                if (intended_pos[0] + self.agent_radius > ox and intended_pos[0] - self.agent_radius < ox + ow and
                        intended_pos[1] + self.agent_radius > oy and intended_pos[1] - self.agent_radius < oy + oh):
                    hit_obstacle = True
                    intended_pos = np.copy(self.agent_pos)
                    break

        if hit_obstacle and self.logger:
            self.logger.log_anomaly("WALL_CLIP", {"coords": intended_pos.tolist()}, self.current_step)
        if hit_boundary and self.logger:
            self.logger.log_anomaly("OUT_OF_BOUNDS", {"coords": intended_pos.tolist()}, self.current_step)

        self.agent_pos = intended_pos

        triggered_bug = False
        bug_info = None
        for bz in self.config.bug_zones:
            bx, by, bw, bh = bz["x"], bz["y"], bz["w"], bz["h"]
            if (bx <= self.agent_pos[0] <= bx + bw and by <= self.agent_pos[1] <= by + bh):
                triggered_bug = True
                bug_info = bz
                if self.logger:
                    self.logger.log_anomaly("BUG_ZONE_TRIGGER",
                                            {"zone_name": bz["name"], "coords": self.agent_pos.tolist(),
                                             "code": bz.get("error_code", "BUG")}, self.current_step)
                break

        if self.logger:
            self.logger.log_position(self.agent_pos[0], self.agent_pos[1])

        prev_health = self.health
        if hit_obstacle:
            self.health -= 5.0
        self.health = max(0.0, self.health)

        next_obs = self._get_obs()
        state_info = {
            "agent_pos": self.agent_pos, "prev_agent_pos": self.prev_agent_pos,
            "player_pos": self.player_pos, "goal_pos": self.goal_pos,
            "health": self.health, "prev_health": prev_health,
            "hit_obstacle": hit_obstacle, "hit_boundary": hit_boundary,
            "triggered_bug": triggered_bug, "bug_zone_info": bug_info,
            "chosen_action": action, "obs": prev_obs, "next_obs": next_obs,
        }
        reward, reward_breakdown = self.reward_generator.calculate_reward(state_info)

        terminated = self.health <= 0.0
        if np.linalg.norm(self.agent_pos - self.goal_pos) < 3.0:
            terminated = True
        truncated = self.current_step >= self.max_steps

        info = {"agent_pos": self.agent_pos.tolist(), "player_pos": self.player_pos.tolist(),
                "health": self.health, "anomaly_detected": triggered_bug,
                "reward_breakdown": reward_breakdown}
        return next_obs, reward, terminated, truncated, info

    def _get_obs(self) -> np.ndarray:
        obs = np.zeros((6,), dtype=np.float32)
        obs[0] = self.agent_pos[0] / self.map_width  # net_x (coordinate)
        obs[1] = self.agent_pos[1] / self.map_height  # net_y (coordinate)
        obs[2] = self.player_pos[0] / self.map_width  # net_player_x (coordinate)
        obs[3] = self.player_pos[1] / self.map_height  # net_player_y (coordinate)
        obs[4] = self.health / 100.0  # net_health (health)
        obs[5] = self.current_step / self.max_steps  # net_tick (time)
        return obs
